error_narrator/__init__.py,sha256=6Z1myiQhJxd8wbwW_EZXdDfJ0g7Q9SvjtrRbN23DrtU,209
error_narrator/narrator.py,sha256=w2HkqJVMiR6MYzy2cLezLgRHGyBCaR2-K53ce5vWMCw,15903
error_narrator-0.2.2.dist-info/METADATA,sha256=rmnY3H1CR6HKD49zNOwtmM9SrY_NAKvzWgoUnpFKygA,3943
error_narrator-0.2.2.dist-info/WHEEL,sha256=b4K_helf-jlQoXBBETfwnf4B04YC67LOev0jo4fX5m8,88
error_narrator-0.2.2.dist-info/RECORD,,
